CREATE SEQUENCE IF NOT EXISTS car_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS showroom_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE c_user
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR(255),
    username  VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_c_user PRIMARY KEY (id)
);

CREATE TABLE car
(
    id          BIGINT           NOT NULL,
    vin         VARCHAR(25)      NOT NULL,
    maker       VARCHAR(25)      NOT NULL,
    model       VARCHAR(25)      NOT NULL,
    model_year  BIGINT           NOT NULL,
    price       DOUBLE PRECISION NOT NULL,
    showroom_id BIGINT           NOT NULL,
    CONSTRAINT pk_car PRIMARY KEY (id)
);

CREATE TABLE showroom
(
    id                             BIGINT       NOT NULL,
    name                           VARCHAR(100) NOT NULL,
    commercial_registration_number BIGINT       NOT NULL,
    manager_name                   VARCHAR(255),
    contact_number                 BIGINT       NOT NULL,
    address                        VARCHAR(255),
    is_delete                      BOOLEAN,
    CONSTRAINT pk_showroom PRIMARY KEY (id)
);

ALTER TABLE showroom
    ADD CONSTRAINT uc_showroom_commercial_registration_number UNIQUE (commercial_registration_number);

ALTER TABLE car
    ADD CONSTRAINT FK_CAR_ON_SHOWROOM FOREIGN KEY (showroom_id) REFERENCES showroom (id);